### ISSUE TITLE
Firebase API Public

### ISSUE THREAD

**Issue by yukisho** [Lost-Ark-Market-Online/LostArk-Market-Web#19]
Your firebase information is public. This is very dangerous and your ``environments`` file should be added to .gitignore so no one can use your api key if you have not changed it.

**Comment by gogodr** [comment]
The keys and ids in the repo are public keys and have very limited access. 

They were in the project since earlier in the project we had a direct firebase implementation using the public key and it was needed for forks of the project to be able to consume de database without extra hoops, but now we migrated the implementation to a Rest API for performance reasons so there is not really need to have it in there. 

I will remove them, thanks.

**Comment by gogodr** [comment]
0b3a20ae68b001113778d016be96d428deff0c1c

**Comment by gogodr** [comment]
Removed in commit: 0b3a20ae68b001113778d016be96d428deff0c1c

**Comment by gogodr** [comment]
On further evaluation, the watcher application procedure still uses a direct firebase integration so there is a need of the public keys to still be in the project. 
They will stay in there until the proper migration from direct implementation to rest API is rolled out for that feature.
