### ISSUE TITLE
What should I do if I want RU data? Or somewhere.

### ISSUE THREAD

**Issue by Watermelon-S** [Lost-Ark-Market-Online/LostArk-Market-Web#23]
I want to be the tool station of RU server

**Comment by gogodr** [comment]
At the moment we are not running the project on the RU server. Mainly because of lack of experience and watchers. 
An internationalization update is also due for the watcher software since right now it only supports scanning in english, but we have a community that uses many other languages. 
Once we implement the internationalization update, and if there is enough demand for it, I can extend the project to also contain the RU community.

**Comment by Watermelon-S** [comment]
I see. Thank you for your reply.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gonzalo ***@***.***&gt;; 
发送时间: 2022年11月4日(星期五) 凌晨3:19
收件人: ***@***.***&gt;; 
抄送: "a&apos;ゞ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-Ark-Market-Online/LostArk-Market-Web] What should I do if I want RU data? Or somewhere. (Issue #23)






At the moment we are not running the project on the RU server. Mainly because of lack of experience and watchers.
An internationalization update is also due for the watcher software since right now it only supports scanning in english, but we have a community that uses many other languages.
Once we implement the internationalization update, and if there is enough demand for it, I can extend the project to also contain the RU community.
