### ISSUE TITLE
Price history/trend

### ISSUE THREAD

**Issue by tyindeepit** [Lost-Ark-Market-Online/LostArk-Market-Web#3]
Since you're getting input from market watcher constantly. I think it's possible to implement price history/trend. It can be just 5-day price history like in-game or a price trend graph.

**Comment by gogodr** [comment]
I am working on it. Right now the problem is to make a method for people to be able to browse that data processed instead of loading the whole collection of entries for each item which would eat up all the read traffic quota we have from firebase. 
Once I figure out a way to do it I will show the data using this kind of charts: 
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/indicators/ema/

**Comment by tyindeepit** [comment]
I agree. There's no need for real-time price graph, just processed data to see the trend. May be 12-hour interval trend dating back 5-7 days?

Keep up the good work. I'll do my part of feeding the screenshots 😊

**Comment by gogodr** [comment]
We now have price history and indicators such as ema and supertrend for every item. ✌
