### ISSUE TITLE
Kudos to you!

### ISSUE THREAD

**Issue by ItsCEED** [Lost-Ark-Market-Online/LostArk-Market-Web#5]
i was working on something like this, but never found time to finish it.

I have a domain bought not long ago, and i can push it over you if you are interested!
lostarkbroker.com

Also, i have applied for a "market watcher"

Also, a  you can easly implement mari, map, crafting profit calculator pretty easy with all the data!

**Comment by gogodr** [comment]
I bought the lostarkmarket.online domain for the project, but if you want to I would appreciate it if you were to do a redirection form your domain to the lostarkmarket.online one so that we can use both easily. ✌
A crafting profit calculator is something I want to tackle on since we have all the data we need right now to do it. 
Right now I am finishing the historical data processing feature, once I finish this I will see what else to tackle next from the backlog. ✌
